sudo: false
language: python
python:
- 2.7_with_system_site_packages
addons:
  apt:
    sources:
    - mopidy-stable
    packages:
    - mopidy
env:
- TOX_ENV=py27
- TOX_ENV=flake8
install:
- pip install tox
script:
- tox -e $TOX_ENV
after_success:
- if [ $TOX_ENV == 'py27' ]; then pip install coveralls; coveralls; fi
deploy:
  provider: pypi
  user: tdemierr
  password:
    secure: H9WTUBjUH/ZwDXU817pzlEQ+sw3GRMywPoQwpJsXMW4Ujn1QR0Iiyp23XFeRM42iI2tLCgAbW2+PNg1uYLHiiMKeuAk0hDXgUXTN0h7uAiFoAxK0aH2Jtq9BlFxrbhaea6iXe5nmNXoMwIBJNXIzmiOqI7GKs4RTxo+J6Ffn9x+ilHXFxFtaIxmvuMaW3SNRIgXF5HZWh1H4tcgPHf9Xq0kEdoTMM8mmI3PKaxnkK18Zvuk3KwoAZUEubDBdH/Xguufaouv7CydL1s2+47d5PjZFmYqFeo3hpMl0jSnBxJndzYgJpNxe4/ZevXFOzR7OlfIFB6GQqlUjCp+TAv4oubrCEtaZ7Uc5tW2UMeFK9TK9+Ln/ol+59xSdTx1DlVZqz9kt3qhcidDrHofl9q4I53HKIW2A+9scXKjGJXM1sP2ALyRXCoRvaKhlpK2AeG/tnvuqO7agwPvnUR1yyO0/WPa4MqGXPcCaO/ZCa7m9nQo78u4/2O3fmqb8OeG0AoT6JuOJmaM8crElb0O52NkT+sZMjOGxt6k2XW9c/SjHC3FlEfIXjEgFntzmqqzVm78X7jDoEg1l+o7PpfyNXAgcQ9Du809kjh9IMHv4yqhN0o9PteLlALValpkYh0odw304U+0qQtdFKJ7yZ4tzgmH+PStUrrU1D9KM+UU+Gr+Qrz0=
  on:
    tags: true
    branch: master
